jwt:
  secret: 6c3cf93a5c2988f5cace02954e9fe7a6e02089cebdc196564361e93ab8f1d62a

spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:6432/auth
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath*:database/initDB.sql
#      data-locations: classpath*:database/populateDB.sql

  jpa:
    database: postgresql
    properties.hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG